tasks:
  - name: Dependencies
    init: |
      sudo apt update
      sudo apt install libnss3 gnupg libxkbfile1 libsecret-1-0 libgtk-3-0 libxss1 libgbm1 xvfb
      npm install
      npm install -g gulp

vscode:
  extensions:
    - ms-vscode.vscode-typescript-tslint-plugin
